# Generated by Django 4.2.1 on 2023-05-04 14:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Drugs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "manufactured_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "expiration_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=200)),
                ("user_email", models.EmailField(max_length=200)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_created=True)),
                (
                    "patient_card_number",
                    models.CharField(default=uuid.uuid4, max_length=8),
                ),
                ("patient_full_name", models.CharField(max_length=250)),
                ("patient_address", models.TextField(max_length=250)),
                ("patient_email", models.EmailField(max_length=254)),
                ("next_of_kin", models.CharField(max_length=200)),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")],
                        default="male",
                        max_length=10,
                    ),
                ),
                ("date_of_birth", models.DateField(default=django.utils.timezone.now)),
                (
                    "date_of_admission",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("discharge_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "patient_mobile_number",
                    models.CharField(
                        blank=True,
                        max_length=13,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Entered mobile number isn't in a right format!",
                                regex="^[0-9]{10,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "next_of_kin_mobile_number",
                    models.CharField(
                        blank=True,
                        max_length=13,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Entered mobile number isn't in a right format!",
                                regex="^[0-9]{10,15}$",
                            )
                        ],
                    ),
                ),
                ("doctor_name", models.CharField(max_length=200)),
                ("doctor_report", models.TextField(max_length=300)),
                (
                    "doctor_report_file_upload",
                    models.FileField(upload_to="upload/patient's files"),
                ),
                ("diagnosis", models.TextField(max_length=250)),
                ("modified", models.DateTimeField(auto_now_add=True)),
                (
                    "drugs_prescribed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient_records.drugs",
                        verbose_name="Drug Prescribed",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Patients",
            },
        ),
        migrations.CreateModel(
            name="Nurses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("next_of_kin", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=13,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Entered mobile number isn't in a right format!",
                                regex="^[0-9]{10,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")],
                        default="female",
                        max_length=10,
                    ),
                ),
                (
                    "employment_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("employment_id", models.CharField(default=uuid.uuid4, max_length=6)),
                ("specialization", models.CharField(max_length=250)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now_add=True)),
                (
                    "patient_attended_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient_records.patient",
                        verbose_name="Patients Treated",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Doctors",
            },
        ),
        migrations.CreateModel(
            name="Doctors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("next_of_kin", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=13,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Entered mobile number isn't in a right format!",
                                regex="^[0-9]{10,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")],
                        default="male",
                        max_length=10,
                    ),
                ),
                (
                    "employment_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("employment_id", models.CharField(default=uuid.uuid4, max_length=6)),
                ("specialization", models.CharField(max_length=250)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now_add=True)),
                (
                    "patient_treated",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient_records.patient",
                        verbose_name="Patients Treated",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Doctors",
            },
        ),
        migrations.CreateModel(
            name="Billing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("description", models.CharField(max_length=200)),
                ("service_bill", models.CharField(max_length=200)),
                ("amount", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("closed", "Closed")],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "Patient_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient_records.patient",
                        verbose_name="Patient Name",
                    ),
                ),
                (
                    "doctor_attending",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient_records.doctors",
                        verbose_name="Attending Doctor",
                    ),
                ),
            ],
        ),
    ]
