# Generated by Django 4.2.1 on 2023-05-04 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patient_records", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="billing",
            options={"verbose_name_plural": "Bills"},
        ),
        migrations.AlterModelOptions(
            name="drugs",
            options={"verbose_name_plural": "Drugs"},
        ),
        migrations.AlterModelOptions(
            name="nurses",
            options={"verbose_name_plural": "Nurses"},
        ),
    ]
